version: '3.8'
services:
  terraform:
    image: hashicorp/terraform:1.3.9
    working_dir: /infra
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}