version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cli: circleci/aws-cli@1.3.1
executors:
  build:
    docker:
      - image: cimg/node:16.13
  deploy:
    docker:
      - image: cimg/python:3.7-node

commands:
  yarn_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  #   テストが必要になった際に復活
  #   build:
  #     executor: build
  #     working_directory: ~/repo
  #     steps:
  #       - checkout
  #       - yarn_install

  deploy:
    executor: deploy
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup
      - yarn_install
      - run:
          name: Set environments
          command: ./deploy/bin/set_environments.sh production
      - run:
          name: generate
          command: yarn generate
      - aws-s3/sync:
          from: dist
          to: s3://saien-nakaya-production-lp
          arguments: "--delete"
      - run:
          name: clear cache from cloudfornt
          command: aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths '/*'

workflows:
  version: 2
  deploy:
    jobs:
      #      - build
      - deploy:
          #          requires:
          #            - build
          filters:
            branches:
              only:
                - main
                - develop
